import { type Location, type TrafficUpdate, type City, type Category } from "@shared/schema";

export interface IStorage {
  getLocationsByCity(city: City): Promise<Location[]>;
  getLocationsByCityAndCategory(city: City, category: Category): Promise<Location[]>;
  getAllLocations(): Promise<Location[]>;
  getTrafficUpdates(city: City): Promise<TrafficUpdate[]>;
}

export class MemStorage implements IStorage {
  private locations: Location[];
  private trafficUpdates: TrafficUpdate[];

  constructor() {
    this.locations = this.initializeLocations();
    this.trafficUpdates = this.initializeTrafficUpdates();
  }

  async getLocationsByCity(city: City): Promise<Location[]> {
    return this.locations.filter(loc => loc.city === city);
  }

  async getLocationsByCityAndCategory(city: City, category: Category): Promise<Location[]> {
    return this.locations.filter(loc => loc.city === city && loc.category === category);
  }

  async getAllLocations(): Promise<Location[]> {
    return this.locations;
  }

  async getTrafficUpdates(city: City): Promise<TrafficUpdate[]> {
    return this.trafficUpdates.filter(update => update.city === city);
  }

  private initializeLocations(): Location[] {
    return [
      // Bangalore - Shopping
      {
        id: "blr-shop-1",
        name: "Commercial Street",
        category: "shopping",
        city: "bangalore",
        address: "Commercial Street, Shivaji Nagar, Bangalore 560001",
        phone: "+91 80 2558 4321",
        hours: "10:00 AM - 9:00 PM",
        description: "One of Bangalore's busiest shopping streets featuring diverse shops for clothing, accessories, footwear, and traditional Indian wear at great prices.",
        rating: 4.3,
        reviewCount: 2845,
        latitude: 12.9823,
        longitude: 77.6072,
        amenities: ["Parking", "ATM", "Food Court"],
        isOpen: true
      },
      {
        id: "blr-shop-2",
        name: "UB City Mall",
        category: "shopping",
        city: "bangalore",
        address: "24, Vittal Mallya Road, Bangalore 560001",
        phone: "+91 80 4173 8888",
        hours: "11:00 AM - 11:00 PM",
        description: "Luxury shopping destination with premium international brands, fine dining restaurants, and an upscale ambiance in the heart of the city.",
        rating: 4.5,
        reviewCount: 1923,
        latitude: 12.9726,
        longitude: 77.5996,
        amenities: ["Valet Parking", "WiFi", "Premium Dining"],
        isOpen: true
      },
      {
        id: "blr-shop-3",
        name: "Phoenix Marketcity",
        category: "shopping",
        city: "bangalore",
        address: "Whitefield Main Road, Mahadevapura, Bangalore 560048",
        phone: "+91 80 3344 4455",
        hours: "10:30 AM - 10:00 PM",
        description: "Massive shopping mall with 600+ brands, multiplex cinema, gaming zones, and diverse food options making it a complete entertainment destination.",
        rating: 4.4,
        reviewCount: 5234,
        latitude: 12.9975,
        longitude: 77.6969,
        amenities: ["Free Parking", "WiFi", "Cinema", "Kids Play Area"],
        isOpen: true
      },
      {
        id: "blr-shop-4",
        name: "Chickpet Market",
        category: "shopping",
        city: "bangalore",
        address: "Chickpet Main Road, Bangalore 560053",
        phone: "+91 80 2670 1234",
        hours: "9:00 AM - 8:00 PM",
        description: "Traditional wholesale market famous for textiles, sarees, jewelry, and ethnic wear at wholesale prices in the old city area.",
        rating: 4.0,
        reviewCount: 987,
        latitude: 12.9691,
        longitude: 77.5838,
        amenities: ["Street Parking", "Traditional Shopping"],
        isOpen: true
      },
      {
        id: "blr-shop-5",
        name: "Orion Mall",
        category: "shopping",
        city: "bangalore",
        address: "Brigade Gateway Campus, Rajajinagar, Bangalore 560055",
        phone: "+91 80 4954 5454",
        hours: "10:00 AM - 10:00 PM",
        description: "Sprawling mall with wide variety of fashion, electronics, home decor stores along with entertainment options and food court.",
        rating: 4.3,
        reviewCount: 3421,
        latitude: 12.9886,
        longitude: 77.5355,
        amenities: ["Multi-level Parking", "WiFi", "Cinema", "Food Court"],
        isOpen: true
      },
      {
        id: "blr-shop-6",
        name: "Garuda Mall",
        category: "shopping",
        city: "bangalore",
        address: "Magrath Road, Ashok Nagar, Bangalore 560025",
        phone: "+91 80 4121 2121",
        hours: "10:30 AM - 9:30 PM",
        description: "Popular neighborhood mall with good mix of retail brands, restaurants, and entertainment options in central Bangalore location.",
        rating: 4.2,
        reviewCount: 2156,
        latitude: 12.9745,
        longitude: 77.6062,
        amenities: ["Parking", "WiFi", "Gaming Zone"],
        isOpen: true
      },
      {
        id: "blr-shop-7",
        name: "VR Bangalore",
        category: "shopping",
        city: "bangalore",
        address: "Whitefield Main Road, Bangalore 560066",
        phone: "+91 80 6940 9409",
        hours: "11:00 AM - 10:00 PM",
        description: "Modern lifestyle destination combining shopping, dining, and entertainment with contemporary architecture and premium brands.",
        rating: 4.6,
        reviewCount: 4123,
        latitude: 12.9899,
        longitude: 77.7478,
        amenities: ["Valet Parking", "WiFi", "Premium Brands", "Events Space"],
        isOpen: true
      },
      {
        id: "blr-shop-8",
        name: "Forum Mall Koramangala",
        category: "shopping",
        city: "bangalore",
        address: "21, Hosur Road, Koramangala, Bangalore 560029",
        phone: "+91 80 4344 9944",
        hours: "10:00 AM - 10:00 PM",
        description: "One of Bangalore's first malls, offering fashion, electronics, books, and a popular food court in vibrant Koramangala.",
        rating: 4.1,
        reviewCount: 2987,
        latitude: 12.9344,
        longitude: 77.6119,
        amenities: ["Parking", "WiFi", "Cinema", "Bookstore"],
        isOpen: true
      },
      {
        id: "blr-shop-9",
        name: "Avenue Road Market",
        category: "shopping",
        city: "bangalore",
        address: "Avenue Road, Bangalore 560002",
        phone: "+91 80 2222 3344",
        hours: "9:30 AM - 8:30 PM",
        description: "Bustling market area known for wholesale and retail of home furnishings, utensils, and household items at competitive prices.",
        rating: 3.9,
        reviewCount: 756,
        latitude: 12.9838,
        longitude: 77.5745,
        amenities: ["Street Parking", "Wholesale Options"],
        isOpen: true
      },
      {
        id: "blr-shop-10",
        name: "Mantri Square Mall",
        category: "shopping",
        city: "bangalore",
        address: "Sampige Road, Malleswaram, Bangalore 560003",
        phone: "+91 80 4041 4041",
        hours: "10:00 AM - 10:00 PM",
        description: "Well-established mall in North Bangalore with diverse retail options, dining, and entertainment facilities.",
        rating: 4.2,
        reviewCount: 1876,
        latitude: 13.0067,
        longitude: 77.5698,
        amenities: ["Parking", "WiFi", "Cinema", "Gaming"],
        isOpen: true
      },

      // Bangalore - Dining
      {
        id: "blr-din-1",
        name: "MTR - Mavalli Tiffin Room",
        category: "dining",
        city: "bangalore",
        address: "11, Lalbagh Road, Bangalore 560027",
        phone: "+91 80 2222 0022",
        hours: "6:30 AM - 11:00 AM, 12:30 PM - 3:00 PM, 7:00 PM - 9:00 PM",
        description: "Legendary South Indian restaurant serving authentic Karnataka cuisine since 1924. Famous for masala dosa, rava idli, and filter coffee.",
        rating: 4.5,
        reviewCount: 8934,
        latitude: 12.9539,
        longitude: 77.5850,
        amenities: ["Wheelchair Accessible", "Takeaway", "Traditional Seating"],
        isOpen: true
      },
      {
        id: "blr-din-2",
        name: "Koshy's",
        category: "dining",
        city: "bangalore",
        address: "39, St. Mark's Road, Bangalore 560001",
        phone: "+91 80 2221 3793",
        hours: "9:00 AM - 11:00 PM",
        description: "Iconic heritage cafe established in 1940, known for its old-world charm, diverse menu, and famous patrons from literary and artistic circles.",
        rating: 4.3,
        reviewCount: 3421,
        latitude: 12.9750,
        longitude: 77.6008,
        amenities: ["WiFi", "Outdoor Seating", "Bar"],
        isOpen: true
      },
      {
        id: "blr-din-3",
        name: "Toit Brewpub",
        category: "dining",
        city: "bangalore",
        address: "298, 100 Feet Road, Indiranagar, Bangalore 560038",
        phone: "+91 80 4124 2253",
        hours: "12:00 PM - 11:30 PM",
        description: "Popular microbrewery and gastropub serving craft beers and continental cuisine in a vibrant, energetic atmosphere.",
        rating: 4.4,
        reviewCount: 6789,
        latitude: 12.9716,
        longitude: 77.6412,
        amenities: ["WiFi", "Bar", "Outdoor Seating", "Live Sports"],
        isOpen: true
      },
      {
        id: "blr-din-4",
        name: "Vidyarthi Bhavan",
        category: "dining",
        city: "bangalore",
        address: "32, Gandhi Bazaar, Basavanagudi, Bangalore 560004",
        phone: "+91 80 2657 7588",
        hours: "6:30 AM - 11:00 AM, 3:00 PM - 7:30 PM",
        description: "Historic establishment famous for crispy masala dosa served with authentic South Indian chutneys and filter coffee.",
        rating: 4.4,
        reviewCount: 5432,
        latitude: 12.9426,
        longitude: 77.5745,
        amenities: ["Takeaway", "Traditional", "Quick Service"],
        isOpen: false
      },
      {
        id: "blr-din-5",
        name: "Karavalli",
        category: "dining",
        city: "bangalore",
        address: "The Gateway Hotel, 66, Residency Road, Bangalore 560025",
        phone: "+91 80 6660 4545",
        hours: "12:30 PM - 3:00 PM, 7:00 PM - 11:30 PM",
        description: "Award-winning coastal cuisine restaurant offering authentic flavors from Kerala, Mangalore, Goa, and Coorg regions.",
        rating: 4.7,
        reviewCount: 2134,
        latitude: 12.9742,
        longitude: 77.6093,
        amenities: ["Valet Parking", "Bar", "Fine Dining", "Wheelchair Accessible"],
        isOpen: true
      },
      {
        id: "blr-din-6",
        name: "Truffles",
        category: "dining",
        city: "bangalore",
        address: "93/A, 3rd Floor, Koramangala, Bangalore 560034",
        phone: "+91 80 4112 2111",
        hours: "11:30 AM - 11:30 PM",
        description: "Casual burger joint and cafe serving generous portions of burgers, steaks, and American comfort food in laid-back setting.",
        rating: 4.3,
        reviewCount: 7821,
        latitude: 12.9352,
        longitude: 77.6245,
        amenities: ["WiFi", "Outdoor Seating", "Takeaway"],
        isOpen: true
      },
      {
        id: "blr-din-7",
        name: "Ebony Restaurant",
        category: "dining",
        city: "bangalore",
        address: "13th Floor, Barton Centre, MG Road, Bangalore 560001",
        phone: "+91 80 4178 4747",
        hours: "12:00 PM - 3:30 PM, 7:00 PM - 11:30 PM",
        description: "Rooftop restaurant offering panoramic city views with multi-cuisine menu and elegant ambiance perfect for special occasions.",
        rating: 4.2,
        reviewCount: 2987,
        latitude: 12.9758,
        longitude: 77.6062,
        amenities: ["Rooftop", "Bar", "Valet Parking", "City Views"],
        isOpen: true
      },
      {
        id: "blr-din-8",
        name: "CTR - Central Tiffin Room",
        category: "dining",
        city: "bangalore",
        address: "283, Margosa Road, Malleswaram, Bangalore 560003",
        phone: "+91 80 2334 1150",
        hours: "7:00 AM - 11:00 AM, 3:30 PM - 7:30 PM",
        description: "Authentic Malleswaram eatery famous for benne masale dosa, set dosa, and traditional South Indian breakfast items.",
        rating: 4.5,
        reviewCount: 4567,
        latitude: 13.0067,
        longitude: 77.5711,
        amenities: ["Quick Service", "Takeaway", "Traditional"],
        isOpen: false
      },
      {
        id: "blr-din-9",
        name: "The Only Place",
        category: "dining",
        city: "bangalore",
        address: "28, Museum Road, Bangalore 560001",
        phone: "+91 80 2559 7797",
        hours: "11:00 AM - 11:00 PM",
        description: "Classic steakhouse serving quality steaks, burgers, and continental dishes for over three decades in cozy setting.",
        rating: 4.4,
        reviewCount: 3654,
        latitude: 12.9759,
        longitude: 77.6026,
        amenities: ["Parking", "Bar", "Takeaway"],
        isOpen: true
      },
      {
        id: "blr-din-10",
        name: "Nagarjuna Restaurant",
        category: "dining",
        city: "bangalore",
        address: "44/1, Residency Road, Bangalore 560025",
        phone: "+91 80 2558 4151",
        hours: "12:00 PM - 3:30 PM, 7:00 PM - 11:00 PM",
        description: "Renowned Andhra cuisine restaurant famous for spicy biryani, authentic curries, and traditional meals served on banana leaf.",
        rating: 4.3,
        reviewCount: 5123,
        latitude: 12.9716,
        longitude: 77.6079,
        amenities: ["Parking", "Takeaway", "Family Dining"],
        isOpen: true
      },

      // Bangalore - Events
      {
        id: "blr-evt-1",
        name: "Bangalore Palace",
        category: "events",
        city: "bangalore",
        address: "Vasanth Nagar, Bangalore 560052",
        phone: "+91 80 2336 0818",
        hours: "10:00 AM - 5:30 PM",
        description: "Historic palace hosting cultural events, concerts, and exhibitions. The palace grounds serve as venue for major music festivals and events.",
        rating: 4.5,
        reviewCount: 12453,
        latitude: 12.9989,
        longitude: 77.5926,
        amenities: ["Parking", "Guided Tours", "Event Space"],
        isOpen: true
      },
      {
        id: "blr-evt-2",
        name: "Chowdiah Memorial Hall",
        category: "events",
        city: "bangalore",
        address: "Gayathri Devi Park Extension, Bangalore 560020",
        phone: "+91 80 2334 0271",
        hours: "Event-based",
        description: "Premier auditorium for classical music, dance performances, and cultural programs with excellent acoustics.",
        rating: 4.3,
        reviewCount: 876,
        latitude: 13.0102,
        longitude: 77.5774,
        amenities: ["Parking", "Wheelchair Accessible", "Air Conditioned"],
        isOpen: false
      },
      {
        id: "blr-evt-3",
        name: "BIEC - Bangalore International Exhibition Centre",
        category: "events",
        city: "bangalore",
        address: "10th Mile, Tumkur Road, Bangalore 560073",
        phone: "+91 80 4699 9999",
        hours: "Event-based",
        description: "Large exhibition center hosting trade shows, conferences, product launches, and major business events.",
        rating: 4.2,
        reviewCount: 2341,
        latitude: 13.0910,
        longitude: 77.5155,
        amenities: ["Ample Parking", "Food Court", "WiFi"],
        isOpen: true
      },
      {
        id: "blr-evt-4",
        name: "Rangoli Metro Art Center",
        category: "events",
        city: "bangalore",
        address: "MG Road Metro Station, Bangalore 560001",
        phone: "+91 80 2559 9036",
        hours: "11:00 AM - 7:00 PM",
        description: "Underground art gallery and cultural space hosting art exhibitions, workshops, and cultural events at Metro station.",
        rating: 4.1,
        reviewCount: 567,
        latitude: 12.9753,
        longitude: 77.6069,
        amenities: ["Metro Access", "WiFi", "Art Gallery"],
        isOpen: true
      },
      {
        id: "blr-evt-5",
        name: "Jayamahal Palace",
        category: "events",
        city: "bangalore",
        address: "Jayamahal Main Road, Bangalore 560046",
        phone: "+91 80 2341 1941",
        hours: "Event-based - Call for bookings",
        description: "Heritage venue perfect for weddings, corporate events, and social gatherings in royal palace setting.",
        rating: 4.6,
        reviewCount: 1234,
        latitude: 13.0028,
        longitude: 77.5952,
        amenities: ["Valet Parking", "Catering", "Heritage Venue"],
        isOpen: false
      },
      {
        id: "blr-evt-6",
        name: "Lahe Lahe",
        category: "events",
        city: "bangalore",
        address: "47th Cross, 8th Block, Jayanagar, Bangalore 560070",
        phone: "+91 80 2663 2424",
        hours: "7:00 PM onwards (Event nights)",
        description: "Open-air venue hosting live music performances, cultural nights, and community events in relaxed garden setting.",
        rating: 4.4,
        reviewCount: 892,
        latitude: 12.9165,
        longitude: 77.5842,
        amenities: ["Outdoor Venue", "Live Music", "Bar"],
        isOpen: true
      },
      {
        id: "blr-evt-7",
        name: "Bangalore International Centre",
        category: "events",
        city: "bangalore",
        address: "7, 4th Main Road, Domlur, Bangalore 560071",
        phone: "+91 80 4340 7777",
        hours: "9:00 AM - 10:00 PM",
        description: "Cultural hub hosting talks, exhibitions, film screenings, and intellectual discussions with library and cafe.",
        rating: 4.5,
        reviewCount: 1567,
        latitude: 12.9607,
        longitude: 77.6387,
        amenities: ["Library", "Cafe", "WiFi", "Parking"],
        isOpen: true
      },
      {
        id: "blr-evt-8",
        name: "Ranga Shankara",
        category: "events",
        city: "bangalore",
        address: "36/2, 8th Cross, JP Nagar, Bangalore 560078",
        phone: "+91 80 2649 3982",
        hours: "Event-based - Check schedule",
        description: "Dedicated theater space for plays, performances, and cultural programs supporting regional and experimental theater.",
        rating: 4.6,
        reviewCount: 1987,
        latitude: 12.9079,
        longitude: 77.5890,
        amenities: ["Parking", "Cafe", "Wheelchair Accessible"],
        isOpen: true
      },
      {
        id: "blr-evt-9",
        name: "Kanteerava Indoor Stadium",
        category: "events",
        city: "bangalore",
        address: "Kasturba Road, Bangalore 560001",
        phone: "+91 80 2226 8821",
        hours: "Event-based",
        description: "Multi-purpose indoor stadium hosting sports events, concerts, exhibitions, and large-scale public events.",
        rating: 4.0,
        reviewCount: 3421,
        latitude: 12.9786,
        longitude: 77.5993,
        amenities: ["Large Capacity", "Parking", "Food Stalls"],
        isOpen: true
      },
      {
        id: "blr-evt-10",
        name: "Venkatappa Art Gallery",
        category: "events",
        city: "bangalore",
        address: "Kasturba Road, Bangalore 560001",
        phone: "+91 80 2286 4483",
        hours: "10:00 AM - 5:00 PM (Closed Mondays)",
        description: "Government art gallery exhibiting paintings, sculptures, and hosting art events and workshops.",
        rating: 4.2,
        reviewCount: 678,
        latitude: 12.9757,
        longitude: 77.5945,
        amenities: ["Free Entry", "Guided Tours", "Art Classes"],
        isOpen: true
      },

      // Bangalore - Hospitals
      {
        id: "blr-hos-1",
        name: "Manipal Hospital",
        category: "hospitals",
        city: "bangalore",
        address: "98, HAL Airport Road, Bangalore 560017",
        phone: "+91 80 2502 4444",
        hours: "24/7 Emergency",
        description: "Multi-specialty hospital with advanced medical facilities, experienced doctors, and comprehensive healthcare services.",
        rating: 4.3,
        reviewCount: 3456,
        latitude: 12.9566,
        longitude: 77.6417,
        amenities: ["24/7 Emergency", "Pharmacy", "Ambulance", "Parking"],
        isOpen: true
      },
      {
        id: "blr-hos-2",
        name: "Apollo Hospital",
        category: "hospitals",
        city: "bangalore",
        address: "154/11, Bannerghatta Road, Bangalore 560076",
        phone: "+91 80 2630 0100",
        hours: "24/7 Emergency",
        description: "Leading tertiary care hospital offering world-class treatment across specialties with state-of-the-art infrastructure.",
        rating: 4.4,
        reviewCount: 5678,
        latitude: 12.8978,
        longitude: 77.5978,
        amenities: ["24/7 Emergency", "ICU", "Pharmacy", "Parking", "Cafeteria"],
        isOpen: true
      },
      {
        id: "blr-hos-3",
        name: "Fortis Hospital",
        category: "hospitals",
        city: "bangalore",
        address: "14, Cunningham Road, Bangalore 560052",
        phone: "+91 80 6621 4444",
        hours: "24/7 Emergency",
        description: "Premium healthcare facility known for cardiac care, neurosciences, and comprehensive medical services.",
        rating: 4.2,
        reviewCount: 2890,
        latitude: 12.9944,
        longitude: 77.5931,
        amenities: ["24/7 Emergency", "Advanced Diagnostics", "Pharmacy", "Parking"],
        isOpen: true
      },
      {
        id: "blr-hos-4",
        name: "Columbia Asia Hospital",
        category: "hospitals",
        city: "bangalore",
        address: "Kirloskar Business Park, Hebbal, Bangalore 560024",
        phone: "+91 80 6614 6614",
        hours: "24/7 Emergency",
        description: "Modern multi-specialty hospital providing quality healthcare with patient-centric approach and advanced technology.",
        rating: 4.1,
        reviewCount: 1987,
        latitude: 13.0358,
        longitude: 77.5970,
        amenities: ["24/7 Emergency", "Pharmacy", "Lab", "Parking"],
        isOpen: true
      },
      {
        id: "blr-hos-5",
        name: "St. John's Medical College Hospital",
        category: "hospitals",
        city: "bangalore",
        address: "Sarjapur Road, Bangalore 560034",
        phone: "+91 80 2206 5000",
        hours: "24/7 Emergency",
        description: "Charitable hospital and medical college providing affordable quality healthcare with experienced medical faculty.",
        rating: 4.3,
        reviewCount: 4321,
        latitude: 12.9256,
        longitude: 77.6336,
        amenities: ["24/7 Emergency", "Medical College", "Pharmacy", "Parking"],
        isOpen: true
      },
      {
        id: "blr-hos-6",
        name: "Narayana Health City",
        category: "hospitals",
        city: "bangalore",
        address: "258/A, Bommasandra, Bangalore 560099",
        phone: "+91 80 7122 2222",
        hours: "24/7 Emergency",
        description: "Large multi-specialty hospital complex offering comprehensive healthcare services at affordable costs.",
        rating: 4.2,
        reviewCount: 6789,
        latitude: 12.8050,
        longitude: 77.6821,
        amenities: ["24/7 Emergency", "Multiple Specialties", "Pharmacy", "Ample Parking"],
        isOpen: true
      },
      {
        id: "blr-hos-7",
        name: "Bangalore Baptist Hospital",
        category: "hospitals",
        city: "bangalore",
        address: "Bellary Road, Hebbal, Bangalore 560024",
        phone: "+91 80 2211 5000",
        hours: "24/7 Emergency",
        description: "Established mission hospital providing compassionate healthcare with focus on patient welfare and community service.",
        rating: 4.0,
        reviewCount: 1654,
        latitude: 13.0351,
        longitude: 77.5887,
        amenities: ["24/7 Emergency", "Pharmacy", "Chapel", "Parking"],
        isOpen: true
      },
      {
        id: "blr-hos-8",
        name: "Sparsh Hospital",
        category: "hospitals",
        city: "bangalore",
        address: "29, P Kalinga Rao Road, Bangalore 560027",
        phone: "+91 80 4344 4444",
        hours: "24/7 Emergency",
        description: "Specialized orthopedic hospital with expertise in joint replacements, sports medicine, and bone care.",
        rating: 4.4,
        reviewCount: 2345,
        latitude: 12.9615,
        longitude: 77.5854,
        amenities: ["24/7 Emergency", "Orthopedic Specialists", "Physiotherapy", "Parking"],
        isOpen: true
      },
      {
        id: "blr-hos-9",
        name: "Cloudnine Hospital",
        category: "hospitals",
        city: "bangalore",
        address: "1533, 9th Cross, Jayanagar, Bangalore 560069",
        phone: "+91 80 4567 8900",
        hours: "24/7 Emergency",
        description: "Specialized maternity and child care hospital with modern NICU facilities and experienced gynecologists.",
        rating: 4.5,
        reviewCount: 3876,
        latitude: 12.9267,
        longitude: 77.5833,
        amenities: ["24/7 Emergency", "NICU", "Pediatrics", "Parking"],
        isOpen: true
      },
      {
        id: "blr-hos-10",
        name: "Vikram Hospital",
        category: "hospitals",
        city: "bangalore",
        address: "No.10, Millers Road, Bangalore 560052",
        phone: "+91 80 2347 1747",
        hours: "24/7 Emergency",
        description: "Multi-specialty hospital known for cardiac care, cancer treatment, and comprehensive healthcare services.",
        rating: 4.1,
        reviewCount: 2567,
        latitude: 12.9927,
        longitude: 77.5867,
        amenities: ["24/7 Emergency", "Cardiology", "Oncology", "Parking"],
        isOpen: true
      },

      // Bangalore - Bus Timing
      {
        id: "blr-bus-1",
        name: "Kempegowda Bus Station (Majestic)",
        category: "bus-timing",
        city: "bangalore",
        address: "Gubbi Thotadappa Road, Bangalore 560009",
        phone: "+91 80 2287 3377",
        hours: "24/7 Operations",
        description: "Main bus terminal for city and intercity buses with extensive connectivity across Karnataka and neighboring states.",
        rating: 3.8,
        reviewCount: 8765,
        latitude: 12.9767,
        longitude: 77.5718,
        amenities: ["Waiting Area", "Food Stalls", "Ticket Counter", "Parking"],
        isOpen: true
      },
      {
        id: "blr-bus-2",
        name: "Shivajinagar Bus Stand",
        category: "bus-timing",
        city: "bangalore",
        address: "Infantry Road, Shivajinagar, Bangalore 560001",
        phone: "+91 80 2286 4377",
        hours: "5:00 AM - 11:00 PM",
        description: "Major city bus stand with routes to central Bangalore areas and connection to metro station.",
        rating: 3.7,
        reviewCount: 2345,
        latitude: 12.9823,
        longitude: 77.6048,
        amenities: ["Metro Connection", "Waiting Area", "Restrooms"],
        isOpen: true
      },
      {
        id: "blr-bus-3",
        name: "Shantinagar Bus Station",
        category: "bus-timing",
        city: "bangalore",
        address: "Shantinagar Main Road, Bangalore 560027",
        phone: "+91 80 2222 8877",
        hours: "5:00 AM - 11:30 PM",
        description: "Important bus terminal for south Bangalore routes and intercity buses to Tamil Nadu.",
        rating: 3.9,
        reviewCount: 1876,
        latitude: 12.9628,
        longitude: 77.6011,
        amenities: ["Waiting Room", "Ticket Counter", "Parking"],
        isOpen: true
      },
      {
        id: "blr-bus-4",
        name: "Yeshwanthpur Satellite Bus Station",
        category: "bus-timing",
        city: "bangalore",
        address: "Tumkur Road, Yeshwanthpur, Bangalore 560022",
        phone: "+91 80 2334 7788",
        hours: "24/7 Operations",
        description: "Satellite bus terminal serving northwest Bangalore with local and long-distance bus services.",
        rating: 3.6,
        reviewCount: 1543,
        latitude: 13.0280,
        longitude: 77.5437,
        amenities: ["Waiting Area", "Food Court", "Parking"],
        isOpen: true
      },
      {
        id: "blr-bus-5",
        name: "Electronic City Bus Depot",
        category: "bus-timing",
        city: "bangalore",
        address: "Electronic City Phase 1, Bangalore 560100",
        phone: "+91 80 2852 4455",
        hours: "5:30 AM - 11:00 PM",
        description: "Bus depot serving IT corridor with frequent services to city center and tech parks.",
        rating: 3.8,
        reviewCount: 2109,
        latitude: 12.8399,
        longitude: 77.6770,
        amenities: ["Shelter", "Digital Boards", "WiFi"],
        isOpen: true
      },
      {
        id: "blr-bus-6",
        name: "K.R. Market Bus Stand",
        category: "bus-timing",
        city: "bangalore",
        address: "K.R. Market, Bangalore 560002",
        phone: "+91 80 2670 9988",
        hours: "5:00 AM - 10:30 PM",
        description: "Busy bus stand near K.R. Market serving old Bangalore areas with extensive city bus network.",
        rating: 3.5,
        reviewCount: 987,
        latitude: 12.9591,
        longitude: 77.5739,
        amenities: ["Market Access", "Waiting Area"],
        isOpen: true
      },
      {
        id: "blr-bus-7",
        name: "Banashankari Bus Terminal",
        category: "bus-timing",
        city: "bangalore",
        address: "Banashankari 2nd Stage, Bangalore 560070",
        phone: "+91 80 2671 1122",
        hours: "5:30 AM - 11:00 PM",
        description: "Major terminal for south Bangalore with metro connectivity and extensive bus routes.",
        rating: 3.9,
        reviewCount: 1678,
        latitude: 12.9250,
        longitude: 77.5462,
        amenities: ["Metro Station", "Parking", "Shops"],
        isOpen: true
      },
      {
        id: "blr-bus-8",
        name: "Kadugodi Bus Stand",
        category: "bus-timing",
        city: "bangalore",
        address: "Whitefield Main Road, Kadugodi, Bangalore 560067",
        phone: "+91 80 2845 6677",
        hours: "5:00 AM - 11:00 PM",
        description: "Bus stand serving Whitefield IT corridor with connections to various parts of Bangalore.",
        rating: 3.7,
        reviewCount: 1234,
        latitude: 13.0078,
        longitude: 77.7567,
        amenities: ["Shelter", "Route Maps", "Parking"],
        isOpen: true
      },
      {
        id: "blr-bus-9",
        name: "Hebbal Bus Stand",
        category: "bus-timing",
        city: "bangalore",
        address: "Bellary Road, Hebbal, Bangalore 560024",
        phone: "+91 80 2341 5566",
        hours: "5:30 AM - 10:30 PM",
        description: "Bus terminal for north Bangalore with routes to airport and surrounding areas.",
        rating: 3.8,
        reviewCount: 1456,
        latitude: 13.0358,
        longitude: 77.5970,
        amenities: ["Waiting Area", "Shops", "Restrooms"],
        isOpen: true
      },
      {
        id: "blr-bus-10",
        name: "Jayanagar 4th Block Bus Stop",
        category: "bus-timing",
        city: "bangalore",
        address: "4th Block, Jayanagar, Bangalore 560011",
        phone: "+91 80 2663 4455",
        hours: "5:00 AM - 11:30 PM",
        description: "Central bus stop in Jayanagar with connections across Bangalore and shopping complex.",
        rating: 4.0,
        reviewCount: 2345,
        latitude: 12.9267,
        longitude: 77.5833,
        amenities: ["Shopping Complex", "Metro Nearby", "Food Outlets"],
        isOpen: true
      },

      // Bangalore - Schools & Colleges
      {
        id: "blr-sch-1",
        name: "Bishop Cotton Boys' School",
        category: "schools",
        city: "bangalore",
        address: "27, St. Mark's Road, Bangalore 560001",
        phone: "+91 80 2221 1913",
        hours: "8:00 AM - 3:30 PM (School Days)",
        description: "Prestigious boys' school established in 1865, known for academic excellence and co-curricular activities.",
        rating: 4.6,
        reviewCount: 876,
        latitude: 12.9743,
        longitude: 77.6008,
        amenities: ["Sports Facilities", "Library", "Labs", "Hostel"],
        isOpen: false
      },
      {
        id: "blr-sch-2",
        name: "National Public School, HSR Layout",
        category: "schools",
        city: "bangalore",
        address: "OMBR Layout, Banaswadi, Bangalore 560043",
        phone: "+91 80 2528 6854",
        hours: "8:00 AM - 3:00 PM (School Days)",
        description: "Premium CBSE school offering holistic education with modern infrastructure and experienced faculty.",
        rating: 4.5,
        reviewCount: 1234,
        latitude: 13.0097,
        longitude: 77.6486,
        amenities: ["Smart Classrooms", "Sports Complex", "Transport", "Labs"],
        isOpen: false
      },
      {
        id: "blr-sch-3",
        name: "Indian Institute of Science (IISc)",
        category: "schools",
        city: "bangalore",
        address: "CV Raman Road, Bangalore 560012",
        phone: "+91 80 2293 2001",
        hours: "9:00 AM - 5:00 PM (Working Days)",
        description: "Premier research institution and university for science and engineering with world-class faculty and facilities.",
        rating: 4.8,
        reviewCount: 2567,
        latitude: 13.0219,
        longitude: 77.5671,
        amenities: ["Research Labs", "Library", "Hostel", "Sports Facilities"],
        isOpen: true
      },
      {
        id: "blr-sch-4",
        name: "Christ University",
        category: "schools",
        city: "bangalore",
        address: "Hosur Road, Bangalore 560029",
        phone: "+91 80 4012 9292",
        hours: "8:30 AM - 4:30 PM (College Days)",
        description: "Prestigious deemed university offering diverse programs with emphasis on holistic development and academic excellence.",
        rating: 4.4,
        reviewCount: 3456,
        latitude: 12.9345,
        longitude: 77.6076,
        amenities: ["Library", "Auditorium", "Sports", "Hostel", "Cafeteria"],
        isOpen: true
      },
      {
        id: "blr-sch-5",
        name: "St. Joseph's College",
        category: "schools",
        city: "bangalore",
        address: "36, Langford Road, Bangalore 560027",
        phone: "+91 80 2221 5368",
        hours: "8:00 AM - 4:00 PM (College Days)",
        description: "Heritage institution known for quality education, strong values, and excellent academic track record.",
        rating: 4.5,
        reviewCount: 1987,
        latitude: 12.9462,
        longitude: 77.5992,
        amenities: ["Library", "Labs", "Sports Grounds", "Chapel"],
        isOpen: true
      },
      {
        id: "blr-sch-6",
        name: "RV College of Engineering",
        category: "schools",
        city: "bangalore",
        address: "Mysore Road, Bangalore 560059",
        phone: "+91 80 2867 2845",
        hours: "8:30 AM - 5:00 PM (College Days)",
        description: "Top engineering college with excellent placement record, modern labs, and experienced faculty.",
        rating: 4.3,
        reviewCount: 2890,
        latitude: 12.9237,
        longitude: 77.4987,
        amenities: ["Labs", "Library", "Hostel", "Sports", "WiFi"],
        isOpen: true
      },
      {
        id: "blr-sch-7",
        name: "The International School Bangalore",
        category: "schools",
        city: "bangalore",
        address: "NAFL Valley, Whitefield, Bangalore 560067",
        phone: "+91 80 2845 5967",
        hours: "8:00 AM - 3:30 PM (School Days)",
        description: "Premier international school offering IB curriculum with state-of-the-art facilities and global perspective.",
        rating: 4.7,
        reviewCount: 765,
        latitude: 12.9926,
        longitude: 77.7418,
        amenities: ["IB Curriculum", "Sports Complex", "Performing Arts", "Transport"],
        isOpen: false
      },
      {
        id: "blr-sch-8",
        name: "Mount Carmel College",
        category: "schools",
        city: "bangalore",
        address: "58, Palace Road, Bangalore 560052",
        phone: "+91 80 2226 1759",
        hours: "8:00 AM - 4:00 PM (College Days)",
        description: "Renowned women's college known for academic excellence, vibrant campus life, and empowering education.",
        rating: 4.4,
        reviewCount: 1654,
        latitude: 12.9914,
        longitude: 77.5928,
        amenities: ["Library", "Auditorium", "Labs", "Sports Facilities"],
        isOpen: true
      },
      {
        id: "blr-sch-9",
        name: "Bangalore International School",
        category: "schools",
        city: "bangalore",
        address: "Geddalahalli, Hennur-Bagalur Road, Bangalore 560077",
        phone: "+91 80 2846 5060",
        hours: "8:00 AM - 3:00 PM (School Days)",
        description: "International school with Cambridge curriculum, modern facilities, and focus on global citizenship.",
        rating: 4.6,
        reviewCount: 987,
        latitude: 13.0848,
        longitude: 77.6465,
        amenities: ["Cambridge Curriculum", "Swimming Pool", "Theatre", "Transport"],
        isOpen: false
      },
      {
        id: "blr-sch-10",
        name: "PES University",
        category: "schools",
        city: "bangalore",
        address: "100 Feet Ring Road, BSK 3rd Stage, Bangalore 560085",
        phone: "+91 80 2672 1983",
        hours: "8:30 AM - 5:00 PM (College Days)",
        description: "Leading private university offering engineering and management programs with industry collaborations.",
        rating: 4.2,
        reviewCount: 3210,
        latitude: 12.9345,
        longitude: 77.5336,
        amenities: ["Modern Labs", "Library", "Hostel", "Sports", "Placement Cell"],
        isOpen: true
      },

      // Mangalore - Shopping (10 locations)
      {
        id: "mng-shop-1",
        name: "City Centre Mall",
        category: "shopping",
        city: "mangalore",
        address: "Hampankatta, Mangalore 575001",
        phone: "+91 824 242 5678",
        hours: "10:00 AM - 9:00 PM",
        description: "Central shopping mall with variety of retail stores, food court, and entertainment options in the heart of city.",
        rating: 4.2,
        reviewCount: 1567,
        latitude: 12.8722,
        longitude: 74.8429,
        amenities: ["Parking", "Food Court", "Cinema", "WiFi"],
        isOpen: true
      },
      {
        id: "mng-shop-2",
        name: "Forum Fiza Mall",
        category: "shopping",
        city: "mangalore",
        address: "Pandeshwar, Mangalore 575001",
        phone: "+91 824 221 1111",
        hours: "10:30 AM - 10:00 PM",
        description: "Modern shopping destination featuring national and international brands, multiplex, and diverse dining options.",
        rating: 4.3,
        reviewCount: 2134,
        latitude: 12.8656,
        longitude: 74.8426,
        amenities: ["Multi-level Parking", "Cinema", "Food Court", "Kids Zone"],
        isOpen: true
      },
      {
        id: "mng-shop-3",
        name: "Central Market",
        category: "shopping",
        city: "mangalore",
        address: "Central Market Road, Mangalore 575001",
        phone: "+91 824 244 3322",
        hours: "8:00 AM - 8:00 PM",
        description: "Traditional market offering fresh produce, local goods, and authentic Mangalorean products at wholesale prices.",
        rating: 4.0,
        reviewCount: 876,
        latitude: 12.8698,
        longitude: 74.8425,
        amenities: ["Fresh Produce", "Local Products", "Wholesale"],
        isOpen: true
      },
      {
        id: "mng-shop-4",
        name: "Bharath Mall",
        category: "shopping",
        city: "mangalore",
        address: "Balmatta Road, Mangalore 575001",
        phone: "+91 824 242 7788",
        hours: "10:00 AM - 9:30 PM",
        description: "Popular shopping center with clothing, electronics, and accessories stores catering to diverse shopping needs.",
        rating: 4.1,
        reviewCount: 1234,
        latitude: 12.8706,
        longitude: 74.8438,
        amenities: ["Parking", "ATM", "Food Outlets"],
        isOpen: true
      },
      {
        id: "mng-shop-5",
        name: "Empire Mall",
        category: "shopping",
        city: "mangalore",
        address: "Car Street, Mangalore 575001",
        phone: "+91 824 220 9988",
        hours: "9:30 AM - 9:00 PM",
        description: "Multi-story shopping complex in busy Car Street area offering variety of products and brands.",
        rating: 3.9,
        reviewCount: 987,
        latitude: 12.8742,
        longitude: 74.8438,
        amenities: ["Central Location", "Parking", "Multiple Floors"],
        isOpen: true
      },
      {
        id: "mng-shop-6",
        name: "Big Bazaar Kankanady",
        category: "shopping",
        city: "mangalore",
        address: "Kankanady, Mangalore 575002",
        phone: "+91 824 224 5566",
        hours: "10:00 AM - 10:00 PM",
        description: "Hypermarket offering groceries, clothing, electronics, and household items under one roof.",
        rating: 4.0,
        reviewCount: 1876,
        latitude: 12.8927,
        longitude: 74.8638,
        amenities: ["Parking", "Home Delivery", "Special Offers"],
        isOpen: true
      },
      {
        id: "mng-shop-7",
        name: "Lulu Mall",
        category: "shopping",
        city: "mangalore",
        address: "NH-66, Kapikad, Mangalore 575008",
        phone: "+91 824 711 1111",
        hours: "10:00 AM - 10:00 PM",
        description: "Massive shopping and entertainment destination with wide range of international brands and family entertainment.",
        rating: 4.5,
        reviewCount: 3456,
        latitude: 12.8247,
        longitude: 74.8946,
        amenities: ["Ample Parking", "Cinema", "Gaming Zone", "Food Court", "Hypermarket"],
        isOpen: true
      },
      {
        id: "mng-shop-8",
        name: "Balmatta Market",
        category: "shopping",
        city: "mangalore",
        address: "Balmatta Road, Mangalore 575001",
        phone: "+91 824 242 3344",
        hours: "9:00 AM - 8:00 PM",
        description: "Traditional shopping area known for textiles, sarees, and local handicrafts at competitive prices.",
        rating: 3.8,
        reviewCount: 654,
        latitude: 12.8703,
        longitude: 74.8443,
        amenities: ["Traditional Shopping", "Local Handicrafts"],
        isOpen: true
      },
      {
        id: "mng-shop-9",
        name: "Hampankatta Shopping Complex",
        category: "shopping",
        city: "mangalore",
        address: "Hampankatta Circle, Mangalore 575001",
        phone: "+91 824 242 5555",
        hours: "10:00 AM - 9:00 PM",
        description: "Busy shopping area with mix of modern stores and traditional shops offering diverse products.",
        rating: 4.0,
        reviewCount: 1098,
        latitude: 12.8720,
        longitude: 74.8430,
        amenities: ["Central Location", "Banking", "Restaurants"],
        isOpen: true
      },
      {
        id: "mng-shop-10",
        name: "Kadri Market",
        category: "shopping",
        city: "mangalore",
        address: "Kadri Road, Mangalore 575002",
        phone: "+91 824 221 6677",
        hours: "8:30 AM - 8:00 PM",
        description: "Local market offering fresh vegetables, fruits, flowers, and daily essentials at affordable prices.",
        rating: 3.9,
        reviewCount: 567,
        latitude: 12.8893,
        longitude: 74.8490,
        amenities: ["Fresh Produce", "Local Market", "Street Parking"],
        isOpen: true
      },

      // Mangalore - Dining (10 locations)
      {
        id: "mng-din-1",
        name: "Machali",
        category: "dining",
        city: "mangalore",
        address: "The Gateway Hotel, Old Port Road, Mangalore 575001",
        phone: "+91 824 666 0420",
        hours: "12:30 PM - 3:00 PM, 7:00 PM - 11:00 PM",
        description: "Premium seafood restaurant offering authentic coastal cuisine with ocean views and elegant ambiance.",
        rating: 4.5,
        reviewCount: 1876,
        latitude: 12.8643,
        longitude: 74.8421,
        amenities: ["Sea View", "Bar", "Valet Parking", "Fine Dining"],
        isOpen: true
      },
      {
        id: "mng-din-2",
        name: "Gajalee",
        category: "dining",
        city: "mangalore",
        address: "Balmatta Road, Mangalore 575001",
        phone: "+91 824 242 6666",
        hours: "12:00 PM - 3:30 PM, 7:00 PM - 11:00 PM",
        description: "Famous for authentic Mangalorean seafood preparations, crab dishes, and traditional coastal flavors.",
        rating: 4.4,
        reviewCount: 2345,
        latitude: 12.8706,
        longitude: 74.8442,
        amenities: ["Seafood Specialty", "Parking", "Family Dining"],
        isOpen: true
      },
      {
        id: "mng-din-3",
        name: "Ideal Ice Cream Parlour",
        category: "dining",
        city: "mangalore",
        address: "Hampankatta Circle, Mangalore 575001",
        phone: "+91 824 244 0833",
        hours: "11:00 AM - 11:00 PM",
        description: "Iconic ice cream parlor since 1970s, famous for unique flavors and traditional recipes. Must-try local favorite.",
        rating: 4.6,
        reviewCount: 4567,
        latitude: 12.8722,
        longitude: 74.8431,
        amenities: ["Outdoor Seating", "Takeaway", "Traditional"],
        isOpen: true
      },
      {
        id: "mng-din-4",
        name: "Palkhi Restaurant",
        category: "dining",
        city: "mangalore",
        address: "KS Rao Road, Mangalore 575003",
        phone: "+91 824 244 8877",
        hours: "11:30 AM - 3:30 PM, 6:30 PM - 11:00 PM",
        description: "Multi-cuisine restaurant known for North Indian and Chinese dishes in comfortable family-friendly setting.",
        rating: 4.2,
        reviewCount: 1654,
        latitude: 12.8776,
        longitude: 74.8453,
        amenities: ["Parking", "Family Dining", "AC"],
        isOpen: true
      },
      {
        id: "mng-din-5",
        name: "Sagar Ratna",
        category: "dining",
        city: "mangalore",
        address: "Lalbagh, Mangalore 575003",
        phone: "+91 824 242 1234",
        hours: "7:00 AM - 10:30 PM",
        description: "Popular South Indian restaurant chain serving authentic dosas, idlis, and traditional breakfast items.",
        rating: 4.1,
        reviewCount: 1987,
        latitude: 12.8755,
        longitude: 74.8468,
        amenities: ["Quick Service", "Takeaway", "Vegetarian"],
        isOpen: true
      },
      {
        id: "mng-din-6",
        name: "Maharaja Family Restaurant",
        category: "dining",
        city: "mangalore",
        address: "Kodailbail, Mangalore 575003",
        phone: "+91 824 242 5678",
        hours: "11:00 AM - 11:00 PM",
        description: "Budget-friendly restaurant offering variety of Indian, Chinese, and continental dishes for families.",
        rating: 4.0,
        reviewCount: 1234,
        latitude: 12.8798,
        longitude: 74.8443,
        amenities: ["Parking", "Family Dining", "Affordable"],
        isOpen: true
      },
      {
        id: "mng-din-7",
        name: "Anmol Restaurant",
        category: "dining",
        city: "mangalore",
        address: "Hampankatta, Mangalore 575001",
        phone: "+91 824 244 2211",
        hours: "7:00 AM - 11:00 PM",
        description: "Casual dining restaurant popular for breakfast, lunch thalis, and North Indian cuisine.",
        rating: 3.9,
        reviewCount: 987,
        latitude: 12.8718,
        longitude: 74.8435,
        amenities: ["Central Location", "Quick Service", "Thali Meals"],
        isOpen: true
      },
      {
        id: "mng-din-8",
        name: "Kudla Restaurant",
        category: "dining",
        city: "mangalore",
        address: "City Centre Mall, Mangalore 575001",
        phone: "+91 824 242 8899",
        hours: "12:00 PM - 3:30 PM, 7:00 PM - 11:00 PM",
        description: "Authentic Mangalorean cuisine in modern setting, serving traditional recipes and coastal specialties.",
        rating: 4.3,
        reviewCount: 1456,
        latitude: 12.8720,
        longitude: 74.8428,
        amenities: ["Mall Parking", "Traditional Cuisine", "AC"],
        isOpen: true
      },
      {
        id: "mng-din-9",
        name: "Summer Sands Beach Resort Restaurant",
        category: "dining",
        city: "mangalore",
        address: "Chota Mangalore, Ullal, Mangalore 575020",
        phone: "+91 824 246 7690",
        hours: "7:00 AM - 11:00 PM",
        description: "Beachfront dining with multi-cuisine menu, fresh seafood, and stunning Arabian Sea views.",
        rating: 4.4,
        reviewCount: 2109,
        latitude: 12.8069,
        longitude: 74.8566,
        amenities: ["Beach View", "Resort Amenities", "Bar", "Parking"],
        isOpen: true
      },
      {
        id: "mng-din-10",
        name: "Hao Ming Chinese Restaurant",
        category: "dining",
        city: "mangalore",
        address: "Balmatta Road, Mangalore 575001",
        phone: "+91 824 244 3355",
        hours: "12:00 PM - 3:00 PM, 6:30 PM - 11:00 PM",
        description: "Specialized Chinese restaurant with authentic flavors, dim sum, and popular Indo-Chinese dishes.",
        rating: 4.2,
        reviewCount: 1321,
        latitude: 12.8709,
        longitude: 74.8440,
        amenities: ["Parking", "Takeaway", "Family Dining"],
        isOpen: true
      },

      // Mangalore - Events (10 locations)
      {
        id: "mng-evt-1",
        name: "Town Hall Mangalore",
        category: "events",
        city: "mangalore",
        address: "Balmatta Road, Mangalore 575001",
        phone: "+91 824 242 5432",
        hours: "Event-based",
        description: "Historic venue hosting cultural programs, conferences, exhibitions, and community events in city center.",
        rating: 4.1,
        reviewCount: 876,
        latitude: 12.8710,
        longitude: 74.8445,
        amenities: ["Auditorium", "Parking", "AC Hall"],
        isOpen: false
      },
      {
        id: "mng-evt-2",
        name: "Tannirbhavi Beach",
        category: "events",
        city: "mangalore",
        address: "Tannirbhavi, Mangalore 575007",
        phone: "+91 824 220 1122",
        hours: "Open 24/7",
        description: "Scenic beach location for outdoor events, festivals, beach sports, and sunset gatherings.",
        rating: 4.3,
        reviewCount: 3456,
        latitude: 12.8856,
        longitude: 74.8047,
        amenities: ["Beach Access", "Parking", "Food Stalls"],
        isOpen: true
      },
      {
        id: "mng-evt-3",
        name: "St. Aloysius Chapel",
        category: "events",
        city: "mangalore",
        address: "Lighthouse Hill Road, Mangalore 575003",
        phone: "+91 824 244 9000",
        hours: "9:00 AM - 5:00 PM",
        description: "Historic chapel with stunning frescoes, hosting religious events, concerts, and cultural programs.",
        rating: 4.6,
        reviewCount: 2134,
        latitude: 12.8748,
        longitude: 74.8430,
        amenities: ["Heritage Site", "Guided Tours", "Photography"],
        isOpen: true
      },
      {
        id: "mng-evt-4",
        name: "Kadri Park",
        category: "events",
        city: "mangalore",
        address: "Kadri Hills, Mangalore 575002",
        phone: "+91 824 222 3344",
        hours: "6:00 AM - 8:00 PM",
        description: "Lush park hosting outdoor events, morning walks, cultural gatherings, and recreational activities.",
        rating: 4.2,
        reviewCount: 1567,
        latitude: 12.8890,
        longitude: 74.8524,
        amenities: ["Open Space", "Walking Paths", "Parking"],
        isOpen: true
      },
      {
        id: "mng-evt-5",
        name: "Mangala Stadium",
        category: "events",
        city: "mangalore",
        address: "Padil, Mangalore 575007",
        phone: "+91 824 228 8899",
        hours: "Event-based",
        description: "Multi-purpose stadium hosting sports events, athletics meets, and large-scale public gatherings.",
        rating: 4.0,
        reviewCount: 987,
        latitude: 12.8563,
        longitude: 74.8897,
        amenities: ["Large Capacity", "Parking", "Facilities"],
        isOpen: true
      },
      {
        id: "mng-evt-6",
        name: "Pilikula Nisargadhama",
        category: "events",
        city: "mangalore",
        address: "Vamanjoor, Mangalore 575028",
        phone: "+91 824 222 1144",
        hours: "9:30 AM - 5:30 PM",
        description: "Eco-educational tourist park hosting cultural events, exhibitions, and nature programs.",
        rating: 4.4,
        reviewCount: 4321,
        latitude: 12.9235,
        longitude: 75.0103,
        amenities: ["Zoo", "Boating", "Museum", "Parking"],
        isOpen: true
      },
      {
        id: "mng-evt-7",
        name: "Dr. TMA Pai International Convention Centre",
        category: "events",
        city: "mangalore",
        address: "Manipal, Udupi 576104",
        phone: "+91 820 292 3000",
        hours: "Event-based",
        description: "State-of-the-art convention center hosting conferences, seminars, exhibitions, and corporate events.",
        rating: 4.5,
        reviewCount: 1876,
        latitude: 13.3499,
        longitude: 74.7869,
        amenities: ["Modern Facilities", "WiFi", "Parking", "Catering"],
        isOpen: true
      },
      {
        id: "mng-evt-8",
        name: "Shri Gokarnanatheshwara Temple",
        category: "events",
        city: "mangalore",
        address: "Kudroli, Mangalore 575003",
        phone: "+91 824 244 0202",
        hours: "6:00 AM - 8:00 PM",
        description: "Beautiful temple hosting religious festivals, cultural events, and annual celebrations.",
        rating: 4.5,
        reviewCount: 3210,
        latitude: 12.8654,
        longitude: 74.8399,
        amenities: ["Temple Complex", "Parking", "Events Hall"],
        isOpen: true
      },
      {
        id: "mng-evt-9",
        name: "Mangalore University Auditorium",
        category: "events",
        city: "mangalore",
        address: "Mangalagangothri, Mangalore 574199",
        phone: "+91 824 228 7287",
        hours: "Event-based",
        description: "University auditorium hosting seminars, cultural programs, and educational events.",
        rating: 4.1,
        reviewCount: 654,
        latitude: 12.7838,
        longitude: 74.9248,
        amenities: ["Auditorium", "Parking", "Campus Access"],
        isOpen: false
      },
      {
        id: "mng-evt-10",
        name: "Panambur Beach",
        category: "events",
        city: "mangalore",
        address: "Panambur, Mangalore 575010",
        phone: "+91 824 242 7788",
        hours: "Open 24/7",
        description: "Popular beach hosting beach festivals, water sports events, and cultural celebrations with facilities.",
        rating: 4.4,
        reviewCount: 5678,
        latitude: 12.9226,
        longitude: 74.8091,
        amenities: ["Beach", "Water Sports", "Food Stalls", "Parking"],
        isOpen: true
      },

      // Mangalore - Hospitals (10 locations)
      {
        id: "mng-hos-1",
        name: "KMC Hospital Ambedkar Circle",
        category: "hospitals",
        city: "mangalore",
        address: "Ambedkar Circle, Mangalore 575001",
        phone: "+91 824 242 1000",
        hours: "24/7 Emergency",
        description: "Multi-specialty teaching hospital with advanced medical facilities and experienced specialists.",
        rating: 4.3,
        reviewCount: 3456,
        latitude: 12.8721,
        longitude: 74.8415,
        amenities: ["24/7 Emergency", "Pharmacy", "ICU", "Parking"],
        isOpen: true
      },
      {
        id: "mng-hos-2",
        name: "Father Muller Medical College Hospital",
        category: "hospitals",
        city: "mangalore",
        address: "Kankanady, Mangalore 575002",
        phone: "+91 824 223 8000",
        hours: "24/7 Emergency",
        description: "Reputed medical college hospital offering comprehensive healthcare with charitable services.",
        rating: 4.4,
        reviewCount: 4567,
        latitude: 12.8937,
        longitude: 74.8603,
        amenities: ["24/7 Emergency", "Medical College", "Pharmacy", "Ambulance"],
        isOpen: true
      },
      {
        id: "mng-hos-3",
        name: "AJ Hospital",
        category: "hospitals",
        city: "mangalore",
        address: "Padil Junction, NH-66, Mangalore 575007",
        phone: "+91 824 242 5575",
        hours: "24/7 Emergency",
        description: "Leading private hospital with modern infrastructure and comprehensive specialty services.",
        rating: 4.2,
        reviewCount: 2890,
        latitude: 12.8534,
        longitude: 74.8798,
        amenities: ["24/7 Emergency", "Advanced Labs", "Pharmacy", "Parking"],
        isOpen: true
      },
      {
        id: "mng-hos-4",
        name: "Yenepoya Hospital",
        category: "hospitals",
        city: "mangalore",
        address: "Deralakatte, Mangalore 575018",
        phone: "+91 824 220 4668",
        hours: "24/7 Emergency",
        description: "Multi-specialty hospital with medical college offering quality healthcare and patient care.",
        rating: 4.1,
        reviewCount: 1987,
        latitude: 12.8416,
        longitude: 74.8801,
        amenities: ["24/7 Emergency", "Medical College", "ICU", "Pharmacy"],
        isOpen: true
      },
      {
        id: "mng-hos-5",
        name: "Unity Hospital",
        category: "hospitals",
        city: "mangalore",
        address: "Kankanady, Mangalore 575002",
        phone: "+91 824 222 0077",
        hours: "24/7 Emergency",
        description: "Well-equipped hospital providing comprehensive medical services with experienced medical staff.",
        rating: 4.0,
        reviewCount: 1654,
        latitude: 12.8930,
        longitude: 74.8625,
        amenities: ["24/7 Emergency", "Pharmacy", "Lab", "Parking"],
        isOpen: true
      },
      {
        id: "mng-hos-6",
        name: "A.J. Institute of Medical Sciences",
        category: "hospitals",
        city: "mangalore",
        address: "Kuntikana, Mangalore 575004",
        phone: "+91 824 222 5533",
        hours: "24/7 Emergency",
        description: "Medical college hospital with teaching facilities and comprehensive healthcare services.",
        rating: 4.2,
        reviewCount: 2345,
        latitude: 12.8611,
        longitude: 74.8976,
        amenities: ["24/7 Emergency", "Medical College", "Pharmacy", "Ambulance"],
        isOpen: true
      },
      {
        id: "mng-hos-7",
        name: "Indiana Hospital",
        category: "hospitals",
        city: "mangalore",
        address: "Kadri Hills, Mangalore 575003",
        phone: "+91 824 220 0300",
        hours: "24/7 Emergency",
        description: "Specialty hospital known for cardiac care, neurology, and orthopedic services.",
        rating: 4.3,
        reviewCount: 1876,
        latitude: 12.8885,
        longitude: 74.8507,
        amenities: ["24/7 Emergency", "Cardiac Care", "Pharmacy", "Parking"],
        isOpen: true
      },
      {
        id: "mng-hos-8",
        name: "Tejasvini Hospital",
        category: "hospitals",
        city: "mangalore",
        address: "Kadri, Mangalore 575002",
        phone: "+91 824 224 9696",
        hours: "24/7 Emergency",
        description: "Women and children's hospital specializing in maternity care, pediatrics, and gynecology.",
        rating: 4.4,
        reviewCount: 2567,
        latitude: 12.8897,
        longitude: 74.8496,
        amenities: ["24/7 Emergency", "Maternity", "NICU", "Pharmacy"],
        isOpen: true
      },
      {
        id: "mng-hos-9",
        name: "Highland Hospital",
        category: "hospitals",
        city: "mangalore",
        address: "Padil, Mangalore 575007",
        phone: "+91 824 220 8800",
        hours: "24/7 Emergency",
        description: "Multi-specialty hospital providing quality healthcare with modern facilities and equipment.",
        rating: 4.1,
        reviewCount: 1432,
        latitude: 12.8548,
        longitude: 74.8812,
        amenities: ["24/7 Emergency", "Pharmacy", "ICU", "Parking"],
        isOpen: true
      },
      {
        id: "mng-hos-10",
        name: "Kasturba Medical College Hospital",
        category: "hospitals",
        city: "mangalore",
        address: "Lighthouse Hill Road, Mangalore 575001",
        phone: "+91 824 244 1000",
        hours: "24/7 Emergency",
        description: "Premier teaching hospital affiliated with Manipal University offering tertiary care services.",
        rating: 4.5,
        reviewCount: 5432,
        latitude: 12.8751,
        longitude: 74.8432,
        amenities: ["24/7 Emergency", "Medical College", "Advanced Care", "Pharmacy"],
        isOpen: true
      },

      // Mangalore - Bus Timing (10 locations)
      {
        id: "mng-bus-1",
        name: "KSRTC Bus Stand Mangalore",
        category: "bus-timing",
        city: "mangalore",
        address: "Bejai, Mangalore 575004",
        phone: "+91 824 222 1777",
        hours: "24/7 Operations",
        description: "Main KSRTC bus terminal for long-distance and interstate bus services with extensive connectivity.",
        rating: 3.8,
        reviewCount: 4567,
        latitude: 12.8643,
        longitude: 74.8487,
        amenities: ["Waiting Room", "Ticket Counter", "Food Stalls", "Parking"],
        isOpen: true
      },
      {
        id: "mng-bus-2",
        name: "State Bank Bus Stand",
        category: "bus-timing",
        city: "mangalore",
        address: "State Bank, Mangalore 575001",
        phone: "+91 824 244 2233",
        hours: "5:00 AM - 11:00 PM",
        description: "City bus stand with local routes and connections to nearby areas and suburbs.",
        rating: 3.7,
        reviewCount: 1876,
        latitude: 12.8734,
        longitude: 74.8419,
        amenities: ["Waiting Area", "City Buses", "Central Location"],
        isOpen: true
      },
      {
        id: "mng-bus-3",
        name: "Pumpwell Bus Stop",
        category: "bus-timing",
        city: "mangalore",
        address: "Pumpwell Circle, Mangalore 575002",
        phone: "+91 824 222 5566",
        hours: "5:30 AM - 10:30 PM",
        description: "Major junction bus stop connecting various parts of Mangalore with frequent bus services.",
        rating: 3.9,
        reviewCount: 1234,
        latitude: 12.8816,
        longitude: 74.8532,
        amenities: ["Shelter", "Multiple Routes", "Shops Nearby"],
        isOpen: true
      },
      {
        id: "mng-bus-4",
        name: "Hampankatta Bus Stop",
        category: "bus-timing",
        city: "mangalore",
        address: "Hampankatta, Mangalore 575001",
        phone: "+91 824 242 3344",
        hours: "5:00 AM - 11:00 PM",
        description: "Central bus stop in commercial area with connections to all parts of the city.",
        rating: 4.0,
        reviewCount: 2345,
        latitude: 12.8722,
        longitude: 74.8429,
        amenities: ["Central Location", "Shopping Access", "Frequent Services"],
        isOpen: true
      },
      {
        id: "mng-bus-5",
        name: "Kankanady Bus Stop",
        category: "bus-timing",
        city: "mangalore",
        address: "Kankanady, Mangalore 575002",
        phone: "+91 824 222 6677",
        hours: "5:30 AM - 10:30 PM",
        description: "Important bus stop serving educational institutions and residential areas.",
        rating: 3.8,
        reviewCount: 987,
        latitude: 12.8927,
        longitude: 74.8615,
        amenities: ["Shelter", "College Access", "Parking"],
        isOpen: true
      },
      {
        id: "mng-bus-6",
        name: "Lalbagh Bus Stop",
        category: "bus-timing",
        city: "mangalore",
        address: "Lalbagh, Mangalore 575003",
        phone: "+91 824 242 7788",
        hours: "5:00 AM - 11:00 PM",
        description: "Busy bus stop connecting residential areas with city center and commercial zones.",
        rating: 3.7,
        reviewCount: 876,
        latitude: 12.8755,
        longitude: 74.8468,
        amenities: ["Shelter", "Route Maps", "Nearby Shops"],
        isOpen: true
      },
      {
        id: "mng-bus-7",
        name: "Kuloor Ferry Bus Stop",
        category: "bus-timing",
        city: "mangalore",
        address: "Kuloor, Mangalore 575013",
        phone: "+91 824 228 9900",
        hours: "6:00 AM - 10:00 PM",
        description: "Bus stop near ferry service connecting to island areas and riverfront locations.",
        rating: 3.6,
        reviewCount: 654,
        latitude: 12.8897,
        longitude: 74.8765,
        amenities: ["Ferry Access", "Riverside", "Parking"],
        isOpen: true
      },
      {
        id: "mng-bus-8",
        name: "Ullal Bus Stand",
        category: "bus-timing",
        city: "mangalore",
        address: "Ullal, Mangalore 575020",
        phone: "+91 824 246 1122",
        hours: "5:30 AM - 10:00 PM",
        description: "Bus terminal serving coastal area with beach access and connections to Kerala border.",
        rating: 3.8,
        reviewCount: 1098,
        latitude: 12.8069,
        longitude: 74.8531,
        amenities: ["Waiting Area", "Beach Access", "Food Stalls"],
        isOpen: true
      },
      {
        id: "mng-bus-9",
        name: "Surathkal Bus Stop",
        category: "bus-timing",
        city: "mangalore",
        address: "Surathkal, Mangalore 575014",
        phone: "+91 824 267 2233",
        hours: "5:00 AM - 10:30 PM",
        description: "Bus stop serving NITK area, beach, and connecting to industrial zones.",
        rating: 3.9,
        reviewCount: 1321,
        latitude: 13.0097,
        longitude: 74.7954,
        amenities: ["College Access", "Beach Nearby", "Shops"],
        isOpen: true
      },
      {
        id: "mng-bus-10",
        name: "Bendoorwell Bus Stop",
        category: "bus-timing",
        city: "mangalore",
        address: "Bendoorwell, Mangalore 575002",
        phone: "+91 824 222 4455",
        hours: "5:30 AM - 10:00 PM",
        description: "Residential area bus stop with connections to city center and surrounding localities.",
        rating: 3.7,
        reviewCount: 765,
        latitude: 12.8889,
        longitude: 74.8579,
        amenities: ["Shelter", "Residential Area", "Parking"],
        isOpen: true
      },

      // Mangalore - Schools & Colleges (10 locations)
      {
        id: "mng-sch-1",
        name: "St. Aloysius College",
        category: "schools",
        city: "mangalore",
        address: "Lighthouse Hill Road, Mangalore 575003",
        phone: "+91 824 244 9000",
        hours: "8:00 AM - 4:00 PM (College Days)",
        description: "Premier autonomous college offering diverse programs with rich heritage and excellent academic record.",
        rating: 4.5,
        reviewCount: 2345,
        latitude: 12.8748,
        longitude: 74.8430,
        amenities: ["Library", "Sports", "Hostel", "Chapel", "Labs"],
        isOpen: true
      },
      {
        id: "mng-sch-2",
        name: "NITK Surathkal",
        category: "schools",
        city: "mangalore",
        address: "Surathkal, Mangalore 575025",
        phone: "+91 824 247 4000",
        hours: "8:00 AM - 5:00 PM (College Days)",
        description: "National Institute of Technology offering prestigious engineering programs with excellent placements.",
        rating: 4.7,
        reviewCount: 3876,
        latitude: 13.0097,
        longitude: 74.7933,
        amenities: ["Beach Campus", "Labs", "Hostel", "Sports Complex", "Library"],
        isOpen: true
      },
      {
        id: "mng-sch-3",
        name: "Canara High School",
        category: "schools",
        city: "mangalore",
        address: "Urwa Store, Mangalore 575006",
        phone: "+91 824 244 1234",
        hours: "8:00 AM - 3:30 PM (School Days)",
        description: "Historic institution providing quality education with strong academic foundation and values.",
        rating: 4.3,
        reviewCount: 1234,
        latitude: 12.8724,
        longitude: 74.8547,
        amenities: ["Sports Ground", "Library", "Labs", "Transport"],
        isOpen: false
      },
      {
        id: "mng-sch-4",
        name: "Mangalore University",
        category: "schools",
        city: "mangalore",
        address: "Mangalagangothri, Mangalore 574199",
        phone: "+91 824 228 7287",
        hours: "9:00 AM - 5:00 PM (Working Days)",
        description: "State university offering undergraduate, postgraduate, and doctoral programs across disciplines.",
        rating: 4.2,
        reviewCount: 2890,
        latitude: 12.7838,
        longitude: 74.9248,
        amenities: ["Campus", "Library", "Hostel", "Sports", "Research Centers"],
        isOpen: true
      },
      {
        id: "mng-sch-5",
        name: "Lourdes Central School",
        category: "schools",
        city: "mangalore",
        address: "Bejai, Mangalore 575004",
        phone: "+91 824 242 4242",
        hours: "8:00 AM - 3:00 PM (School Days)",
        description: "CBSE school known for academic excellence, sports achievements, and holistic development.",
        rating: 4.4,
        reviewCount: 1567,
        latitude: 12.8662,
        longitude: 74.8456,
        amenities: ["Sports Facilities", "Labs", "Library", "Transport"],
        isOpen: false
      },
      {
        id: "mng-sch-6",
        name: "Sahyadri College of Engineering",
        category: "schools",
        city: "mangalore",
        address: "Adyar, Mangalore 575007",
        phone: "+91 824 227 7777",
        hours: "8:30 AM - 5:00 PM (College Days)",
        description: "Engineering college offering quality technical education with modern infrastructure and placements.",
        rating: 4.1,
        reviewCount: 1987,
        latitude: 12.8463,
        longitude: 74.9084,
        amenities: ["Labs", "Library", "Hostel", "WiFi", "Placement Cell"],
        isOpen: true
      },
      {
        id: "mng-sch-7",
        name: "Rosario Cathedral School",
        category: "schools",
        city: "mangalore",
        address: "Pandeshwar, Mangalore 575001",
        phone: "+91 824 242 5678",
        hours: "8:00 AM - 3:30 PM (School Days)",
        description: "Heritage Catholic school providing value-based education with strong academic tradition.",
        rating: 4.3,
        reviewCount: 1098,
        latitude: 12.8656,
        longitude: 74.8420,
        amenities: ["Chapel", "Sports", "Library", "Labs"],
        isOpen: false
      },
      {
        id: "mng-sch-8",
        name: "Father Muller Homoeopathic Medical College",
        category: "schools",
        city: "mangalore",
        address: "Kankanady, Mangalore 575002",
        phone: "+91 824 222 1481",
        hours: "8:00 AM - 4:00 PM (College Days)",
        description: "Homoeopathic medical college with hospital facilities offering quality medical education.",
        rating: 4.2,
        reviewCount: 876,
        latitude: 12.8937,
        longitude: 74.8600,
        amenities: ["Hospital", "Library", "Hostel", "Labs"],
        isOpen: true
      },
      {
        id: "mng-sch-9",
        name: "St. Agnes College",
        category: "schools",
        city: "mangalore",
        address: "Bendur, Mangalore 575002",
        phone: "+91 824 221 6960",
        hours: "8:00 AM - 4:00 PM (College Days)",
        description: "Women's college known for academic excellence and empowering education since 1921.",
        rating: 4.4,
        reviewCount: 1654,
        latitude: 12.8876,
        longitude: 74.8546,
        amenities: ["Library", "Labs", "Hostel", "Sports", "Chapel"],
        isOpen: true
      },
      {
        id: "mng-sch-10",
        name: "The Oxford School",
        category: "schools",
        city: "mangalore",
        address: "Kodialbail, Mangalore 575003",
        phone: "+91 824 242 9999",
        hours: "8:00 AM - 3:00 PM (School Days)",
        description: "Modern CBSE school with focus on academic excellence and overall personality development.",
        rating: 4.3,
        reviewCount: 987,
        latitude: 12.8785,
        longitude: 74.8432,
        amenities: ["Smart Classes", "Sports", "Transport", "Labs", "Library"],
        isOpen: false
      }
    ];
  }

  private initializeTrafficUpdates(): TrafficUpdate[] {
    return [
      // Bangalore Traffic Updates
      {
        id: "blr-trf-1",
        city: "bangalore",
        routeName: "MG Road to Whitefield",
        status: "heavy",
        eta: "45-55 mins",
        lastUpdated: "2 mins ago"
      },
      {
        id: "blr-trf-2",
        city: "bangalore",
        routeName: "Electronic City to Koramangala",
        status: "moderate",
        eta: "25-30 mins",
        lastUpdated: "5 mins ago"
      },
      {
        id: "blr-trf-3",
        city: "bangalore",
        routeName: "Hebbal to Silk Board",
        status: "heavy",
        eta: "60-75 mins",
        lastUpdated: "1 min ago"
      },
      {
        id: "blr-trf-4",
        city: "bangalore",
        routeName: "Indiranagar to Airport",
        status: "moderate",
        eta: "35-40 mins",
        lastUpdated: "3 mins ago"
      },
      {
        id: "blr-trf-5",
        city: "bangalore",
        routeName: "Jayanagar to MG Road",
        status: "low",
        eta: "15-20 mins",
        lastUpdated: "4 mins ago"
      },
      {
        id: "blr-trf-6",
        city: "bangalore",
        routeName: "Banashankari to Koramangala",
        status: "moderate",
        eta: "20-25 mins",
        lastUpdated: "6 mins ago"
      },

      // Mangalore Traffic Updates
      {
        id: "mng-trf-1",
        city: "mangalore",
        routeName: "Hampankatta to Panambur Beach",
        status: "low",
        eta: "15-18 mins",
        lastUpdated: "3 mins ago"
      },
      {
        id: "mng-trf-2",
        city: "mangalore",
        routeName: "Kankanady to City Centre",
        status: "moderate",
        eta: "12-15 mins",
        lastUpdated: "2 mins ago"
      },
      {
        id: "mng-trf-3",
        city: "mangalore",
        routeName: "Ullal to NITK Surathkal",
        status: "low",
        eta: "25-30 mins",
        lastUpdated: "5 mins ago"
      },
      {
        id: "mng-trf-4",
        city: "mangalore",
        routeName: "Pumpwell to Kadri",
        status: "moderate",
        eta: "10-12 mins",
        lastUpdated: "4 mins ago"
      },
      {
        id: "mng-trf-5",
        city: "mangalore",
        routeName: "Bejai to Mangalore University",
        status: "low",
        eta: "20-25 mins",
        lastUpdated: "7 mins ago"
      },
      {
        id: "mng-trf-6",
        city: "mangalore",
        routeName: "State Bank to Lalbagh",
        status: "low",
        eta: "8-10 mins",
        lastUpdated: "6 mins ago"
      }
    ];
  }
}

export const storage = new MemStorage();
